### PR TITLE
chore(lint): Fix super linter (again)

### PR DESCRIPTION
**Pull request by MaxMustermann2**
The super linter workflow is running differently between a branch push and a pull request. As a consequence, we see a failure on the [branch here](https://github.com/ExocoreNetwork/exocore/actions/runs/8169365199/job/22498737480) when a run on the corresponding pull request passed. This change attempts to fix the issue.

### CODE REVIEW

**Comment by MaxMustermann2** [comment]
On the `develop` branch, these Lint items were run.

```
BASH
BASH_EXEC
DOCKERFILE_HADOLINT
GITHUB_ACTIONS
GITLEAKS
JSON
MARKDOWN
PROTOBUF
SHELL_SHFMT
YAML
```

Of these, the failures are `BASH`, `DOCKERFILE_HADOLINT`, `GITLEAKS`, `MARKDOWN`, `SHELL_SHFMT`, `YAML`.

On this pull request, the items that run are as follows.
```
BASH
BASH_EXEC
CHECKOV
DOCKERFILE_HADOLINT
GITHUB_ACTIONS
GITLEAKS
MARKDOWN
PROTOBUF
SHELL_SHFMT
YAML
```

All of these passed, including the ones that previously failed on `develop`. 

Note that the JSON check is not run within this PR, but it was run on `develop`. It is because this PR disables the JSON check since we don't have any non-generated JSON files beyond the lint configuration. 

The PR adds back the IaC (Infrastructure as Code) check and ensures it passes and skips generated files.

|         | JSON | CHECKOV |
|---------|----------|----------|
|develop | :white_check_mark: | :x: (skipped) |
|this PR | :x: (skipped) | ✅  |

**Comment by MaxMustermann2** [comment]
Files which have noteworthy changes to review:

- `Dockerfile`: addition of `HEALTHCHECK` in commit 2f597f54c6d46339f530677a8a7e5000ebeb57f5
- `go.mod`: upgrade of protobuf to fix a [vulnerability](https://github.com/advisories/GHSA-8r3f-844c-mc37) in commit da20a211ce70924eb484d49a08a53bfdac0ba775
- `networks/local/exocore/Dockerfile`: pinned versions, unprivileged user addition, absolute paths and health check in commits 2f597f54c6d46339f530677a8a7e5000ebeb57f5 and 2fa89d09982f9239b154cbbf8b7c74758dc1860d 
- `Makefile`: change the keyring backend for localnet and upgrade go releaser version (unused at this point) to 1.21 in commit 5d0dde2647dbdfcc9bef92e270a27c86223743ee
- `network/init-node.sh`: delete seeds added by binary in commit 73e27d32004c36def8a440d58db63fc22aff8933

**Review by TimmyExogenous — APPROVED** [review]
LGTM

**Review by adu-web3 — APPROVED** [review]
LGTM, excellent work!

**Review by mikebraver — APPROVED** [review]
LGTM

**Pull request merged**
