### PR TITLE
fix(oracle):update params cache in agc when update params

### PR DESCRIPTION
**Pull request by leonz789**
## Description

When params is updated from tx, the cache of params in aggregatorContext should be updated correspondingly.
----

Closes #XXX

## Summary by CodeRabbit

- **New Features**
  - Updated cache commit method to inform users when messages, validators, and parameters are updated.

- **Bug Fixes**
  - Enhanced parameter updates during cache commits to ensure the aggregator context reflects the latest parameters.

- **Tests**
  - Improved tests for parameter updates, including additional setup, teardown, and mock configurations.

### CODE REVIEW

**Comment by leonz789** [comment]
fix issue: #135

**Comment by cloud8little** [comment]
@leonz789 could you fix the UT failure?

**Comment by cloud8little** [comment]
Test passed. RegisterAsset after token is added to oracle params successfully with this commit https://github.com/ExocoreNetwork/exocore/pull/136/commits/f894ccf673548985aafcb9f4621b6d6749158348 .

**Review by cloud8little — APPROVED** [review]

**Review by bwhour — APPROVED** [review]
looks good.

**Review by MaxMustermann2 — APPROVED** [review]

**Pull request merged**
