### PR TITLE
feat(assets): remove total supply

### PR DESCRIPTION
**Pull request by MaxMustermann2**
The total supply variable for staking assets has been removed. Instead, this should be managed on the client chain.

## Summary by CodeRabbit

- **New Features**
	- Updated the `IAssets` interface to improve clarity by renaming parameters related to token supply from `tvlLimit` to `totalSupply`.
	- Introduced a new function, `getTotalSupply`, to retrieve the total supply of a specific token on a client chain.

- **Bug Fixes**
	- Improved error handling to ensure that deposited amounts do not exceed the total supply, enhancing the robustness of asset management.

- **Documentation**
	- Updated comments across various files to reflect the new terminology and clarify the implications of total supply in relation to token deposits.

### CODE REVIEW

**Comment by MaxMustermann2** [comment]
Related: ExocoreNetwork/exocore-contracts#93

**Review by TimmyExogenous — APPROVED** [review]

**Review by bwhour — APPROVED** [review]
it looks good.

**Comment by MaxMustermann2** [comment]
To be merged with https://github.com/ExocoreNetwork/exocore-contracts/pull/93

**Review by adu-web3 — APPROVED** [review]

**Review by TimmyExogenous — APPROVED** [review]

**Review by bwhour — APPROVED** [review]
It looks good.

**Pull request merged**
